### ISSUE TITLE
Deviation from strtod

### ISSUE THREAD

**Issue by mrks** [fastfloat/fast_float#113]
The readme states

> It parses floating-point numbers expecting a locale-independent format equivalent to what is used by std::strtod in the default ("C") locale.

I noticed some difference between strtod and fast_float:

* fast_float does not ignore leading whitespace [as defined for strtod](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strtod.html).
* fast_float does not accept a leading `0x` or `+`
* For 1e999, `strtod` sets `errno = ERANGE`. fast_float returns `inf` and `std::errc{}` (i.e., no error). The other two libraries that I checked (absl::from_chars and boost::lexical_cast) also return an error.

Maybe the documentation could be extended to reflect the differences between strtod and fast_float?

**Comment by lemire** [comment]
> fast_float does not ignore leading whitespace as defined for strtod.

That's a per the `from_char` specification found, e.g., in the [Microsoft documentation](https://docs.microsoft.com/en-us/cpp/standard-library/charconv-functions?view=msvc-160):   `When parsing chars, whitespace isn't ignored. Unlike strtod(), for example, the buffer must start with a valid numeric representation.`


> fast_float does not accept a leading 0x or +

[The `+` sign](https://en.cppreference.com/w/cpp/utility/from_chars) is forbidden: `the plus sign is not recognized outside of the exponent (only the minus sign is permitted at the beginning)`.

We do not support hexadecimal integers or hexadecimal floats at this time. Pull requests are invited.

> For 1e999, strtod sets errno = ERANGE. fast_float returns inf and std::errc{} (i.e., no error)

Right. This is deliberate on my part. My view is that 1e999 is best represented as (positive) infinity.

Node (JavaScript):

<img width="223" alt="Screen Shot 2021-09-21 at 11 24 34 AM" src="https://user-images.githubusercontent.com/391987/134199803-e61363ff-fa6b-4167-967b-3ca6c24d2251.png">

Python:

<img width="108" alt="Screen Shot 2021-09-21 at 11 26 13 AM" src="https://user-images.githubusercontent.com/391987/134200062-845e71c5-aafc-477b-bc10-15ebb3455b75.png">


I am open to changing this behaviour, but I'd like an open debate about it. Please open a specific issue if you think that the current behaviour should be changed.

I will close this issue and edit the README to address your concerns.

Thanks.

**Comment by lemire** [comment]
I have removed any allusion to strtod in the README regarding the format specification, but note that I was paraphrasing the standard. It is strtod with some some changes (such as the leading `+`). That is what we try to follow. If we deviate from the standard, please submit an issue.

<img width="791" alt="Screen Shot 2021-09-21 at 11 51 32 AM" src="https://user-images.githubusercontent.com/391987/134204320-e3b01327-2778-456d-b31c-81a2bb5bfbec.png">

**Comment by lemire** [comment]
Thanks. Please keep reporting issues.
