### ISSUE TITLE
Cross-compilation for arm-none-eabi target

### ISSUE THREAD

**Issue by danngreen** [fastfloat/fast_float#121]
Hi, very nice project!

I've found that two changes need to be made in order to cross-compile for a "bare-metal" ARM target using arm-none-eabi-gcc (that is, the [gcc arm embedded toolchain](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm)).

1) In float_common.h, there is this block:

https://github.com/fastfloat/fast_float/blob/b15abc92382bc9c7e318d12d35ab8e17d4a941f7/include/fast_float/float_common.h#L47-L53

With every version of the toolchain from 10.3.1 going back to at least 5.4, endian.h is located in machine/endian.h, so line 47 needs to match a macro that for the ARM target. I've experimented and found both ` || defined (__arm__)` and ` || defined (__ARM_EABI__)` work, but I'm not sure which is proper (nor do I know where this file is located with propriety non-gcc-based ARM compilers).

2) In digit_comparison.h:
https://github.com/fastfloat/fast_float/blob/b15abc92382bc9c7e318d12d35ab8e17d4a941f7/include/fast_float/digit_comparison.h#L88-L89

The arm-none-eabi-g++ compiler complains `no matching function for call to 'min(int32_t&, int)'`. Explicitly casting the integer constant to the same type as the variable works, and seems to be stylistically similar to other casts in this file:

```
cb(am, std::min(shift, int32_t(64)));
```

If these changes seem helpful to others, I'm happy to issue a pull request. Or try different solutions if this breaks someone else's build. In any case, thanks for the great project!

**Comment by lemire** [comment]
@danngreen Please do submit a PR. It seems entirely reasonable.

**Comment by jwakely** [comment]
See #122 and #123 which fix both these.

**Comment by jwakely** [comment]
In #122 I fixed the `min` deduction with `std::min<int32_t>(shift, 64)` but I can change it to the cast if you prefer that.

For the header, it would be better to detect newlib not just arm, so that it also fixes it for risc-v, cris-elf, and countless other targets that don't match the `__arm__` macro. But #123 has what I think is a better fix anyway.

**Comment by danngreen** [comment]
Excellent, yes it did occur to me to do something like what you did in #123 (looking for the required symbols first), so I'm glad to see you did that. I can confirm this compiles with the arm-none-eabi. Thanks!

**Comment by jwakely** [comment]
Those PRs have been merged, so I hope arm-none-eabi works now and this can be closed, @danngreen

**Comment by lemire** [comment]
Please verify.

**Comment by danngreen** [comment]
Yes, thank you, it builds now.
