### ISSUE TITLE
Feature Request: parsing until delimiter

### ISSUE THREAD

**Issue by spannella** [fastfloat/fast_float#135]
Hi a really common use-case for parsing numbers from text is that the number part is part of a much longer block of character data that is delimited with some character. I wanted to ask the recommended approach in this case. Should one first search for that character then call this function or is there a way to have this function determine the end at the same time as calculating the number preventing multiple passes on the same data.
Example:
```
double d;
const char* buf = "234532.3426362,7869234.9823,324562.645";
const char* ptr_char_after_delimiter = parse_float_delimited(buf, 38, 0, ',', d);
```
With signature:
`const char* parse_float_delimited(const char* data, size_t datalen, size_t offset, char delimiter, double& d)`

Just looking to see your thoughts on the best way to go about this.

**Comment by lemire** [comment]
> Hi a really common use-case for parsing numbers from text is that the number part is part of a much longer block of character data that is delimited with some character. 

Yes. As in JSON or CSV files.

>  I wanted to ask the recommended approach in this case.

The function already advances the pointer for you so you can proceed in the following manner...

```C++
  const std::string input =   "234532.3426362,7869234.9823,324562.645";
  double result;
  auto answer = fast_float::from_chars(input.data(), input.data()+input.size(), result);
  if(answer.ec != std::errc()) { 
    // check error 
  }
  // we have result == 234532.3426362.
  if(answer.ptr[0] != ',') {
    // unexpected delimiter 
  }
  answer = fast_float::from_chars(answer.ptr + 1, input.data()+input.size(), result);
  if(answer.ec != std::errc()) {
    // check error 
  }
  // we have result == 7869234.9823.
  if(answer.ptr[0] != ',') {
    // unexpected delimiter 
  }
  answer = fast_float::from_chars(answer.ptr + 1, input.data()+input.size(), result);
  if(answer.ec != std::errc()) { 
    // check error 
  }
  // we have result == 324562.645.
```

Evidently, you might want to write cleaner code with more abstraction. It could be done with a simple loop...

```C++
  while(pointer < end_pointer) {
    auto answer = fast_float::from_chars(pointer, end_pointer, result);
    if(answer.ec != std::errc()) {
        std::cerr << "error while parsing" << std::endl;
        break;
    }
    std::cout << "parsed: " << result << std::endl;
    pointer = answer.ptr;
    if ((answer.ptr < end_pointer) && (*pointer == ',')) {
      pointer++;
    }
  }
```

> Should one first search for that character then call this function or is there a way to have this function determine the end at the same time as calculating the number preventing multiple passes on the same data.

I think you  might have missed the part where the function already returns a pointer to the first character not matching the pattern.
