### ISSUE TITLE
Emscripten fails to build

### ISSUE THREAD

**Issue by SirLynix** [fastfloat/fast_float#136]
Despite
```c
#if (defined(__x86_64) || defined(__x86_64__) || defined(_M_X64)   \
       || defined(__amd64) || defined(__aarch64__) || defined(_M_ARM64) \
       || defined(__MINGW64__)                                          \
       || defined(__s390x__)                                            \
       || (defined(__ppc64__) || defined(__PPC64__) || defined(__ppc64le__) || defined(__PPC64LE__)) \
       || defined(__EMSCRIPTEN__))
#define FASTFLOAT_64BIT
```

Emscripten cannot compile float_common.h because it lacks `__uint128_t` type.
```
/home/runner/work/ShaderLang/xmake-global/.xmake/packages/f/fast_float/v3.4.0/a7eb886d1d7c4953b530471c8df35d9b/include/fast_float/float_common.h:[19](https://github.com/NazaraEngine/ShaderLang/runs/7670366002?check_suite_focus=true#step:10:20)2:3: error: unknown type name '__uint128_t'
  __uint128_t r = ((__uint128_t)a) * b;
  ^
/home/runner/work/ShaderLang/xmake-global/.xmake/packages/f/fast_float/v3.4.0/a7eb886d1d7c4953b530471c8df35d9b/include/fast_float/float_common.h:192:[21](https://github.com/NazaraEngine/ShaderLang/runs/7670366002?check_suite_focus=true#step:10:22): error: use of undeclared identifier '__uint1[28](https://github.com/NazaraEngine/ShaderLang/runs/7670366002?check_suite_focus=true#step:10:29)_t'
  __uint128_t r = ((__uint128_t)a) * b;
                    ^
2 errors generated.
/home/runner/work/ShaderLang/ShaderLang/emsdk-cache-debug-static/emsdk-main/fastcomp/emscripten/emcc.py:854: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  newargs = [arg for arg in newargs if arg is not '']
/home/runner/work/ShaderLang/ShaderLang/emsdk-cache-debug-static/emsdk-main/fastcomp/emscripten/emcc.py:974: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  newargs = [a for a in newargs if a is not '']
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting
```

Since I'm only using fast_float to parse float from string, I don't need the 128bits `full_multiplication` utility (I think?)

**Comment by lemire** [comment]
Emscripten builds 32-bit executables, so you definitively do not want to set `FASTFLOAT_64BIT`.

**Comment by lemire** [comment]
Have you tried...


```
#elif (defined(__i386) || defined(__i386__) || defined(_M_IX86)   \
     || defined(__arm__) || defined(_M_ARM)                   \
     || defined(__MINGW32__) || defined(__EMSCRIPTEN__))
#define FASTFLOAT_32BIT
```

?

Note that the performance may not be great because with wasm, you are effectively emulating a 32-bit system on top of your 64-bit system. This means that all the cheap operations that your system can do become significantly (like 2x) more expensive. I have not tested it, obviously, but you should expect significantly less performance compared to native code.

**Comment by SirLynix** [comment]
> Emscripten builds 32-bit executables, so you definitively do not want to set `FASTFLOAT_64BIT`.

I'm not, this is the library code:
https://github.com/fastfloat/fast_float/blob/main/include/fast_float/float_common.h#L14

> Note that the performance may not be great because with wasm, you are effectively emulating a 32-bit system on top of your 64-bit system. This means that all the cheap operations that your system can do become significantly (like 2x) more expensive. I have not tested it, obviously, but you should expect significantly less performance compared to native code.


Not an issue since I'm not even using this function, I'm only parsing float from string.

> Have you tried...
> 
> ```
> #elif (defined(__i386) || defined(__i386__) || defined(_M_IX86)   \
>      || defined(__arm__) || defined(_M_ARM)                   \
>      || defined(__MINGW32__) || defined(__EMSCRIPTEN__))
> #define FASTFLOAT_32BIT
> ```

I'll try, I'm using fast_float from https://xmake.io so I first have to try to patch the library from the [fast_float](https://github.com/xmake-io/xmake-repo/blob/master/packages/f/fast_float/xmake.lua) file.

Thanks for the reply.

**Comment by SirLynix** [comment]
Seems good: https://github.com/xmake-io/xmake-repo/pull/1386

**Comment by lemire** [comment]
Please update to 3.5.0, it should solve your issue.

**Comment by lemire** [comment]
Closing. Please re-open if there is a problem.

**Comment by SirLynix** [comment]
Thanks!

**Comment by SirLynix** [comment]
Nope (https://github.com/xmake-io/xmake-repo/runs/7678495252?check_suite_focus=true), see #137

**Comment by lemire** [comment]
Try with 3.5.1.

Note that we do not actually support emscripten. It is untested, so at your own risks. We only support what we test.

**Comment by lemire** [comment]
This is very cool 
https://sirlynixvanfrietjes.be/2020/01/14/cpp-moderne-les-accents/

**Comment by lemire** [comment]
> Also I can't re-open the issue since you closed it

Technically, yes, but one can 'reopen' it through a new issue number. :-)

**Comment by SirLynix** [comment]
> Try with 3.5.1.

3.5.1 is good 🎉 
https://github.com/xmake-io/xmake-repo/runs/7686549596?check_suite_focus=true

> Note that we do not actually support emscripten. It is untested, so at your own risks. We only support what we test.

It should be backed by my [own test suite](https://github.com/NazaraEngine/ShaderLang), if I succeed to run it with emscripten.

> This is very cool
> https://sirlynixvanfrietjes.be/2020/01/14/cpp-moderne-les-accents/

Thanks a lot! 😊
