### ISSUE TITLE
Single header for release 3.9.0 is named fastfloat.h instead of fast_float.h

### ISSUE THREAD

**Issue by linusnilssonatuppmax** [fastfloat/fast_float#171]
Minor "issue" (rather inconvenience...). The releases prior to 3.9.0 appears to name the single header file "fast_float.h" vs "fastfloat.h" in version 3.9.0 (currently latest as far as I can tell). Becomes a slight issue for us who automate builds.

https://github.com/fastfloat/fast_float/releases/download/v3.9.0/fastfloat.h
https://github.com/fastfloat/fast_float/releases/download/v3.8.1/fast_float.h
https://github.com/fastfloat/fast_float/releases/download/v3.4.0/fast_float.h

Thanks to everyone for a great library.

**Comment by lemire** [comment]
Sorry. I will fix this right away.

**Comment by lemire** [comment]
Fixed  at https://github.com/fastfloat/fast_float/releases/tag/v3.9.0
