### ISSUE TITLE
fast_float for x86 fails on basictest

### ISSUE THREAD

**Issue by txgk** [fastfloat/fast_float#174]
Here are a build & test logs for x86 builder: https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/967461

Other architectures pass all tests including basictest (see [upgrade MR for fast_float package in Alpine Linux repositories](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/43926)).

fast_float version: 3.9.0

**Comment by lemire** [comment]
Verified. I will be releasing a patch after https://github.com/fastfloat/fast_float/pull/175 goes green.

**Comment by lemire** [comment]
I am issuing a release.

**Comment by lemire** [comment]
See https://github.com/fastfloat/fast_float/releases/tag/v3.10.0

**Comment by txgk** [comment]
Much appreciate :)
