### ISSUE TITLE
simple_decimal_conversion.h can be deleted

### ISSUE THREAD

**Issue by nigeltao** [fastfloat/fast_float#195]
`include/fast_float/simple_decimal_conversion.h` looks like it's no longer used (and can be deleted), as of commit fc0c8680a55a6e9cdd8934df366c43d9e051aa3c "Implement the big-integer arithmetic algorithm".

In fact, it no longer even compiles, since it refers to a `struct decimal` type, whose definition was deleted in that commit.

**Comment by lemire** [comment]
Thank you!!!
