### ISSUE TITLE
Please bundle Apache 2.0 license in the releases as the license requires

### ISSUE THREAD

**Issue by vlsi** [fastfloat/fast_float#201]
The license requires to give a copy of the license when redistributing the software:

> See https://www.apache.org/licenses/LICENSE-2.0
> 4.a You must give any other recipients of the Work or Derivative Works a copy of this License; and

Even though fast_float.h in the releases includes a link to http://www.apache.org/licenses/LICENSE-2.0, the link is not a copy as the link might become inaccessible, so the recipients might fail to receive "a copy of the License".

Ideally, the full text of Apache-2.0 should be included in `fast_float.h` as it seems to be "single-file release artifact" (10KiB license vs 110KiB implementation).

As an alternative, it might work if you add a separate LICENSE with full Apache-2.0 text side by side with `fast_float.h` in the releases.

Just in case, here's the opinion of the Apache Software Foundation: https://issues.apache.org/jira/browse/LEGAL-642

**Comment by lemire** [comment]
Pull request invited.

**Comment by lemire** [comment]
The release do include the APACHE license. If you think there is an issue, please produce a pull request.
