### ISSUE TITLE
Release fastfloat.h does not include BOOST license

### ISSUE THREAD

**Issue by alugowski** [fastfloat/fast_float#204]
The release asset for the [5.0.0 release](https://github.com/fastfloat/fast_float/releases/tag/v5.0.0) does not include the newly added Boost license.

https://github.com/fastfloat/fast_float/releases/download/v5.0.0/fastfloat.h

**Comment by alugowski** [comment]
This may or may not help your workflow: I use an [`on-release.yml`](https://github.com/alugowski/task-thread-pool/blob/main/.github/workflows/on-release.yml) GitHub Action to upload a single file as a release asset whenever I (manually) cut a release. Copy your amalgamation creation and test steps in there and you could automate the creation and upload of fastfloat.h.

**Comment by alugowski** [comment]
That brings up a question. `fastfloat.h` itself does not have a version number inside it. Since 5.0.0 should have the Boost license and that file does not, what version is that file?

**Comment by lemire** [comment]
I'll issue a patch release.

Pull requests are invited regarding better tooling.

**Comment by lemire** [comment]
I updated the asset. It was a user error on my part: I updated an outdated header file. Thanks for reporting it.

**Comment by alugowski** [comment]
> Pull requests are invited regarding better tooling.

https://github.com/fastfloat/fast_float/pull/205
