### ISSUE TITLE
warning: C4459: declaration of 'uint' hides global declaration

### ISSUE THREAD

**Issue by VioletGiraffe** [fastfloat/fast_float#211]
Inconsequential, but slightly annoying warning at line 700 of the latest `fast_float.h` release. The following declaration clashes with a global one from Qt:
` using uint = typename binary_format<T>::equiv_uint;`

So if you happen to include Qt and then include `fast_float.h`, you'll get this warning, at least with MSVC. A trivial fix would be to rename the type to something more unique, like `fast_float_uint`.

**Comment by lemire** [comment]
Will do.

**Comment by VioletGiraffe** [comment]
Thank you!
