### ISSUE TITLE
incomplete type is not allowed

### ISSUE THREAD

**Issue by breyerml** [fastfloat/fast_float#215]
If I compile fast_float with a (very) new clang++ (clang version 17.0.0 (https://github.com/intel/llvm.git `15f5ac37bb52cde9133f8e8b69e33b5fe8e68c65`)), I get an error:

```c++
include/fast_float/bigint.h(579): error: incomplete type is not allowed
```
The displayed line in the bitint.h header is:
```c++
size_t large_length = sizeof(large_power_of_5) / sizeof(limb);
````
and the reason for the error in clang++ is that `large_power_of_5` is an incomplete type (according to clang++).

If I remove the template from the `pow5_tables` struct, it compiles.

**Comment by lemire** [comment]
I am closing this. The latest release of LLVM as of July 10th 2023 is LLVM 16. There is no release candidate available for LLVM 17 at this time.

Unreleased compilers tend to have bugs.


There might be a bug in the library that is exposed by a compiler and if so, we are interested in identifying it and fix it. However, we cannot be expected to support unreleased compilers.
