### ISSUE TITLE
Support for multiple decimal points

### ISSUE THREAD

**Issue by thbeu** [fastfloat/fast_float#223]
First things first: Thank you for this library!

I see that `parse_options_t` supports a single character only as decimal point, so for example either `','` xor `'.'`. My intention is to both convert `3.1416` and `3,1416` to floating point number and not caring about the decimal point of the actual locale. Is there any shortcut within the library?

**Comment by lemire** [comment]
> Is there any shortcut within the library?

No. I think that a library like `fast_float` is the wrong place where to put such functionality. You should preprocess your files.
