### ISSUE TITLE
`ascii_number.h` is closing `namespace` incorrectly

### ISSUE THREAD

**Issue by Ahmad-S792** [fastfloat/fast_float#240]
Hi,

Was looking into `ascii_number.h` file from WebKit source and noticed that closing `}` for `namespace` was missing.

WebKit Source: https://github.com/WebKit/WebKit/blob/5c17946e30a84685b0c48e0657f5b3f12b9afd17/Source/WTF/wtf/fast_float/ascii_number.h#L20

So I looked into source file from this repo and it is missing two `}` unlike WebKit source.

So just wanted to raise this issue. :-)

Thanks!

**Comment by Ahmad-S792** [comment]
Just to add when I add missing (I am using `VSCode` builtin function to highlight closing functions, so it might be 'VSCode' issue), I get following error:

```urce/WTF/wtf/fast_float/ascii_number.h:408:1: error:
      extraneous closing brace ('}')
} // namespace fast_float
^

**Comment by lemire** [comment]
I am going to close this. If you think that there is an unclosed namespace, I invite you to issue a pull request *or* to provide an analysis. As things stand, I only have a claim that there is faulty unclosed bracket...  I need more evidence that there is a problem.

Note that this library is in widespread use.

**Comment by Ahmad-S792** [comment]
> The plugin is just confused by this code:
> 
> https://github.com/fastfloat/fast_float/blob/ff7cb4426320d8297b2e9e01d8fd2723d7368469/include/fast_float/ascii_number.h#L283-L287
> 
> There are two opening braces there, but only one needs to be closed. If your editor doesn't understand the C++ preprocessor groups, it will think they both need to be closed.

Most likely this is the case, I do have C++ extensions. Will try to find culprit. :-)
