### ISSUE TITLE
Suggestion: provide from_chars_advanced overload or other function name that takes parsed_number_string_t<UC> argument

### ISSUE THREAD

**Issue by zejal** [fastfloat/fast_float#248]
Idea would be to allow for existing parsing code and avoid copy pasting remainder of from_chars_advanced function.
Existing parser code would fill the parsed_number_string structure as appropriate.

**Comment by lemire** [comment]
It is difficult to discuss these things in the abstract. My recommendation is that you make a pull request and we can look at the code.

**Comment by zejal** [comment]
Not hugely familiar with github at this stage, unfortunately.
Based on last released fast_float.hpp you'd have:

`template<typename T, typename UC>
FASTFLOAT_CONSTEXPR20
from_chars_result_t<UC> from_chars_advanced(const parsed_number_string_t<UC>& pns, T &value)  noexcept  {
   answer.ec = std::errc(); // be optimistic
  // same lines as in existing from_chars_advanced.
  // ...
}
`

**Comment by lemire** [comment]
@zejal [Can you propose a patch](https://www.shellhacks.com/create-patch-diff-command-linux/)?

**Comment by zejal** [comment]
Sure, I'll do my best to get familiar with how github works to work on changes.
