### ISSUE TITLE
Question regarding the generalization of this algorithm

### ISSUE THREAD

**Issue by tgross35** [fastfloat/fast_float#250]
The first section of ["Fast Number Parsing Without Fallback"](https://arxiv.org/abs/2212.06644) mentions the following:

>  We have that w × 10<sup>−343</sup> < 2<sup>−1074</sup> for all w < 2<sup>64</sup>.

This same comparison is also mentioned in section 9.2 of ["Number Parsing at a Gigabyte per Second"](https://arxiv.org/abs/2101.11408). This formula is relevant in the derivation of the `smallest_power_of_ten` constant, which must be specified in order to generalize the algorithm.

My question that is relevant for generalization: what is `64` in equation? I.e., what quantity does this number describe?

For context, please see discussion starting at: https://github.com/fastfloat/fast_float/pull/167#issuecomment-2195467913.

This is a general question about the algorithm implemented in this library, as described in the papers, that is applicable to understanding the enclosed code as well as expanding upon the algorithm. If this is not a suitable place to ask for clarification about this library's inspiration, I would appreciate a suggestion as to what a better channel is.

(the answer to this question may be helpful if C++23 bfloat16_t / float16_t / float128_t are added at any point, as in https://github.com/fastfloat/fast_float/issues/148).

**Comment by lemire** [comment]
From the second paragraph of the manuscript, we introduce $w$ as such an integer $w \in [1, 2^{64})$. The inequation $w < 2^{64}$ is just a restatement of this fact.

I am going to close this issue as I believe it is more of a discussion than an issue. I recommend taking question to the discussion section of the GitHub repository.
