### ISSUE TITLE
Build warning on Clang with -Wdeprecated-redundant-constexpr-static-def

### ISSUE THREAD

**Issue by stephenberry** [fastfloat/fast_float#254]
out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated

Enabling `-Wdeprecated-redundant-constexpr-static-def` with warnings as errors causes fast_float to not build on Clang.

Fixing this should make the code cleaner as well.

**Comment by lemire** [comment]
@stephenberry pull request invited!

**Comment by stephenberry** [comment]
I think to support C++11 you would need macros around the old expressions. Do you want this?

**Comment by lemire** [comment]
The library is C++11 and we do not want to change this.

Using macros is acceptable.

**Comment by dalle** [comment]
I can't reproduce this issue anymore, any more details on versions used @stephenberry?

**Comment by stephenberry** [comment]
This issue was reported for version `6.1.3`, perhaps someone fixed it. Are you making sure to build with C++17 or later?

**Comment by dalle** [comment]
This was fixed in #268 for release 6.1.5.

**Comment by dalle** [comment]
Thank you for your report, I'm closing this issue.
