### ISSUE TITLE
max_mantissa_double problem

### ISSUE THREAD

**Issue by wjr-z** [fastfloat/fast_float#258]
1 << 53 that's equal with 0x20000000000000, not 0x10000000000000.
Maybe this's an error ?

**Comment by lemire** [comment]
If you believe that there is a bug, please provide a test case where the library gives an incorrect result. Note that this library has been in production for many years without any issue.

**Comment by lemire** [comment]
Oh I see. Reopening.

**Comment by wjr-z** [comment]
> 哦，我明白。重新。

I mean an error of performance. Because the range of his fast path is smaller than the correct one

**Comment by lemire** [comment]
Yes. I think that you are correct.
