### ISSUE TITLE
Feature request: Library version number macro

### ISSUE THREAD

**Issue by jrade** [fastfloat/fast_float#273]
It would be useful if the fastfloat library had macros with the library version number.
Almost all other libraries provide that. For instance:

The Boost library collection ver. 1.85.0 has a header Version.hpp that contains
``#define BOOST_VERSION 108500``

The Eigen library ver. 3.4.0 has a header macros.hpp that contains
``#define EIGEN_WORLD_VERSION 3``
``#define EIGEN_MAJOR_VERSION 4``
``#define EIGEN_MINOR_VERSION 0``

In the FreeType library ver. 2.13.3 the main header freetype.h contains
``#define FREETYPE_MAJOR  2``
``#define FREETYPE_MINOR  13``
``#define FREETYPE_PATCH  3``

etc.

**Comment by lemire** [comment]
Agreed. It is a worthwhile feature to add.
