### ISSUE TITLE
Feature request: Add allow_leading_plus and skip_white_space in chars_format

### ISSUE THREAD

**Issue by dalle** [fastfloat/fast_float#275]
* Remove/deprecate the defines `FASTFLOAT_ALLOWS_LEADING_PLUS` and `FASTFLOAT_SKIP_WHITE_SPACE`.
* Add `allow_leading_plus` and `skip_white_space` in `chars_format`.
* [Add an additional `from_chars_advanced` for integer types where the format options can be set.]

There may be different needs in different parts of the program using the fast_float library.

**Comment by lemire** [comment]
Pull request invited.

**Comment by dalle** [comment]
Working on a PR for this, I also found some issues with is_space and "nan"/"inf" parsing for non `char` strings.

**Comment by dalle** [comment]
I have created a branch (issue275-deprecate-feature-macros) which is based on changes in #279
