### ISSUE TITLE
Build error with clang+mingw

### ISSUE THREAD

**Issue by Gei0r** [fastfloat/fast_float#45]
When building rapidyaml (which uses fast_float) with clang+mingw on windows, I get the following error message:

```
FAILED: CMakeFiles/ryml.dir/src/c4/yml/tree.cpp.obj
D:\User\Adrian\Programmierung\3rdParty\rapidyaml\Clang-Windows\bin\clang++.exe  -I../src -I../ext/c4core/src -O3 -DNDEBUG -std=c++11 -MD -MT CMakeFiles/ryml.dir/src/c4/yml/tree.cpp.obj -MF CMakeFiles\ryml.dir\src\c4\yml\tree.cpp.obj.d -o CMakeFiles/ryml.dir/src/c4/yml/tree.cpp.obj -c ../src/c4/yml/tree.cpp
In file included from ../src/c4/yml/tree.cpp:1:
In file included from ../src\c4/yml/tree.hpp:10:
In file included from ../ext/c4core/src\c4/charconv.hpp:50:
In file included from ../ext/c4core/src\c4/ext/fast_float.hpp:14:
In file included from ../ext/c4core/src\c4/ext/./fast_float/include/fast_float/fast_float.h:44:
In file included from ../ext/c4core/src\c4/ext/./fast_float/include/fast_float/parse_number.h:3:
In file included from ../ext/c4core/src\c4/ext/./fast_float/include/fast_float/ascii_number.h:9:
../ext/c4core/src\c4/ext/./fast_float/include/fast_float/float_common.h:168:16: error: use of undeclared identifier '_umul128'
  answer.low = _umul128(a, b, &answer.high); // _umul128 not available on ARM64
               ^
```
`_umul128()` is declared in `intrin.h`, but it is not included in `fast_float/float_common.h` due to the following lines:
```c++
#if ((defined(_WIN32) || defined(_WIN64)) && !defined(__clang__))
#include <intrin.h>
#endif
```
So I think the condition should be changed, perhaps to `#ifdef __MINGW32__`?

**Comment by lemire** [comment]
> clang+mingw on windows

I am not familiar with this particular platform. We support and test for gcc/mingw, and clangcl (clang on visual studio), but not clang/mingw at the moment.

Of course, before we support a platform, we should be able to test on it.



>  I think the condition should be changed, perhaps to #ifdef __MINGW32__?

If you are using clang, then I would expect `__clang__` to be defined. And if you have clang, I would expect that you do not need `<intrin.h>`. You also should not be calling `_umul128`.

**Comment by lemire** [comment]
Can you tell me whether your system is 32 bits or 64 bits?

**Comment by lemire** [comment]
Issue reproduced at https://github.com/fastfloat/fast_float/pull/46

**Comment by Gei0r** [comment]
The system and the compiler 64 bit.

> If you are using clang, then I would expect `__clang__` to be defined.

It is.
> And if you have clang, I would expect that you do not need <intrin.h>.

Looks like it's required for `_umul128()`.
> You also should not be calling _umul128.

But it's done in `full_multiplication()` in `float_common.h`.

**Comment by lemire** [comment]
@Gei0r Yes. I understand that it is not working currently. My comments had to do with what ought to happen. 

I will fix this issue soon.  Your issue is valid and needs to be fixed.

**Comment by Gei0r** [comment]
Ah ok, sorry for mis-understanding.

**Comment by lemire** [comment]
Please update to v0.4.0. It should solve the issue. If not, please re-open another issue.

CI tests were added.

**Comment by Gei0r** [comment]
Works out, thank you!
