### ISSUE TITLE
Minor implementation question re: compute_float()

### ISSUE THREAD

**Issue by aldanor** [fastfloat/fast_float#47]
As I was skimming through source code, I've noticed this:

https://github.com/fastfloat/fast_float/blob/2940ec0458622f88d68bf8af4b476e400f5e7ace/include/fast_float/simple_decimal_conversion.h#L306-L311

Wonder why this `0xFF` is not `binary::infinite_power()` instead? (or is there a part I'm missing)

**Comment by lemire** [comment]
Looks to me like an oversight. See https://github.com/fastfloat/fast_float/pull/48
