### ISSUE TITLE
anonymous namespace in headers

### ISSUE THREAD

**Issue by drubbo** [fastfloat/fast_float#54]
https://github.com/fastfloat/fast_float/blob/6c27435fbc4644757ab1a3b00df9ecb3a106c358/include/fast_float/parse_number.h#L16

Use `namespace detail` instead?
Applies to every unnamed namespace in header files.

**Comment by lemire** [comment]
Can you please elaborate? E.g., can you provide an example where you would encounter a problem using the library in its current state, or maybe how you would get compiler warnings?

I do not see how the unnamed namespace can trigger an ODR violation.

**Comment by drubbo** [comment]
It doesn't trigger a compiler error or warning, but in fact every translation unit will use a different instance of whatever's in the unnamed namespace. The unnamed namespace there isn't hiding anything, everything is still accessible by anyone including the headers and usable as if it was in the enclosing namespace. As a rule of thumb, just don't.

https://stackoverflow.com/questions/23652156/how-would-use-of-unnamed-namespaces-in-headers-cause-odr-violations

**Comment by lemire** [comment]
I have renamed the issue. I agree with you that there is not much benefit and that we might as well use a named namespace. There is no ODR violation, however.

To be fixed.

(Pull request invited.)
