### ISSUE TITLE
Single header implementation

### ISSUE THREAD

**Issue by xelatihy** [fastfloat/fast_float#85]
It would be nice to have a single header implementation for quick inclusion in other projects. If this were to be of interest, I can cobble together a small python script that will do the job fine, by simply concatenating the header files in inclusion order and removing the local includes.

**Comment by lemire** [comment]
Please do. Pull request invited.

**Comment by lemire** [comment]
A single-header file has been included in the last release thanks to your script.

https://github.com/fastfloat/fast_float/releases/download/v1.1.2/fast_float.h

Closing.
