### ISSUE TITLE
use std::from_chars_result as return type of from_chars

### ISSUE THREAD

**Issue by igagis** [fastfloat/fast_float#89]
Currently the `from_chars()` function returns `fast_float::from_chars_result` which is fully identical to `std::from_chars_result`. Even `ec` field is of type `std::errc` (i.e. non-`fast_float` custom type).

Make `from_chars()` return `std::from_chars_result`.
Remove the `fast_float::from_chars_result` type.

EDIT: the `std::from_chars_result` is available in `gcc` implementation of `C++17`.

**Comment by lemire** [comment]
Note that `fast_float` only requires C++11. The issue can still be resolved, but would have to be conditional to detecting C++17.

**Comment by igagis** [comment]
ok, then I think it is not needed that much
