### ISSUE TITLE
Unspecified Behavior in Multi-Digit Optimizations

### ISSUE THREAD

**Issue by Alexhuszagh** [fastfloat/fast_float#94]
I've noticed a similar issue in [fast-float-rust](https://github.com/aldanor/fast-float-rust/issues/28), where checking the bounds of the array produces undefined behavior (in Rust), and similar behavior (unspecified) exists in `fast_float`.

Quoting the C++14 standard:

> If two pointers p and q of the same type point to different objects that are not members of the same object or elements of the same array or to different functions, or if only one of them is null, the results of p<q, p>q, p<=q, and p>=q are unspecified.

Therefore, the following code is unspecified behavior (according to [cppreference](https://en.cppreference.com/w/c/language/operator_comparison), it is undefined behavior, however, I am not a language lawyer, so I am unsure of the true semantics).

https://github.com/fastfloat/fast_float/blob/fe1ce5805331d9edae6fe71f10e0b38c3ac4bbe7/include/fast_float/ascii_number.h#L118-L123

Specifically, since `pend` is one-past-the-end of the array, the last valid point of comparison, the compiler could optimize this as always being true, since `p + 8 <= pend` must always be true, an undesirable outcome.

The compliant solution is as follows:

```cpp
#include <iterator>
...

  if ((std::distance(p, pend) >= 8) && is_made_of_eight_digits_fast(p)) {
    i = i * 100000000 + parse_eight_digits_unrolled(p); // in rare cases, this will overflow, but that's ok
    p += 8;
    if ((std::distance(p, pend) >= 8) && is_made_of_eight_digits_fast(p)) {
      i = i * 100000000 + parse_eight_digits_unrolled(p); // in rare cases, this will overflow, but that's ok
      p += 8;
    }
  }
```

Another example in `parse_decimal` also needs to be patched.

**Comment by lemire** [comment]
Yes. You are correct, this is (technically) undefined behaviour. Thanks for pointing it out.

**Comment by lemire** [comment]
I expect that your fix is correct.
