### ISSUE TITLE
unneeded includes

### ISSUE THREAD

**Issue by jrahlf** [fastfloat/fast_float#97]
- `ascii_number.h`, `decimal_to_binary.h` include `<cstdio>` but they don't use any IO functions
- `parse_number.h` includes `<cassert>` but does not use assert (static_assert does not count)
- `ascii_number` includes `<iterator>` which seems unused as well (edit: iterator is actually used)

https://github.com/fastfloat/fast_float/blob/898f54f30a7be1d1890cb6d2b7d53914369b1fd3/include/fast_float/ascii_number.h#L4

**Comment by lemire** [comment]
Pull request invited!
