### ISSUE TITLE
constexpr

### ISSUE THREAD

**Issue by jrahlf** [fastfloat/fast_float#98]
I think the entire thing can be made constexpr (even if std::from_chars is not), you only need to replace memcpy with bitcast (needs c++20).
Would be a nice addition.

**Comment by lemire** [comment]
At this time, we aim for C++11 support. Of course, we could branch at compile-time based on detected C++20 support. Pull request invited.

**Comment by jrahlf** [comment]
Throwing constexpr around it works out of the box with GCC11, even without changing `memcpy` to `bit_cast`. I suspect this might be a GCC extension.
```c++
constexpr double tryParse(std::string_view input)
{
    double result{};
    fast_float::from_chars_result parseResult = fast_float::from_chars(input.data(), input.data() + input.size(), result);
    if (parseResult.ec != std::errc()) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    return result;
}

static_assert(tryParse("1.0") == 1.0);
static_assert(tryParse("3.14156") == 3.14156);
static_assert(tryParse("3.14156") != 3.1415600000001);
static_assert(std::isnan(tryParse("hellothere")));    // technically isnan is not constexpr but seems to work
```
To make it correct, the functions `read_u64` and `write_u64` have to be changed because they `memcpy` between pointer to char and uint64_t.

On the upside, we can get rid of doctest and replace all runtime tests with compile time asserts. :D

Will see if I can make a PR.

**Comment by lemire** [comment]
Solved thanks to @jrahlf (with tests)

If you'd like to get listed as a contributor, just submit a PR adding your name to the CONTRIBUTORS file.
